### ISSUE TITLE
dominant(img.data) = null

### ISSUE THREAD

**Issue by mahlu** [michaelrhodes/huey#8]
dominant(img.data) of a black and white .png image always result to null?

**Comment by michaelrhodes** [comment]
Yeah, this is the intended behaviour because greyscale images don’t have a visible hue. I originally wrote this module to basically do what [the demo](http://michaelrhodes.github.io/huey/) does, ie. find a background colour that can be laid over an image without causing a visual clash. In the case of greyscale images I’d just use one of the fifty shades of grey. Your issue is tangentially related to issue [#5](https://github.com/michaelrhodes/huey/issues/5) though, and I think `./lib/each.js` could be modified to address both.

**Comment by michaelrhodes** [comment]
I actually made this behaviour the default in `3.0.0` (Feb 2019) but forgot to say anything 😬
